spring:
  application:
    name: config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hellofeiwu/config-repo.git
          force-pull: true
          default-label: main
#          这里不写上这个default-label的话，其默认的值是master，但是现在的github不一定是master

server:
  port: 6001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/