spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hellofeiwu/config-repo.git
          force-pull: true
          default-label: main

server:
  port: 6000